// @effect-diagnostics nodeBuiltinImport:off
import { assert, describe, it } from "@effect/vitest";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import { chmod, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { tmpdir } from "node:os";
import { ProviderDriverKind, ProviderInstanceId, EnvironmentId } from "@t3tools/contracts";
import * as ServerConfig from "../config.ts";
import { ServerEnvironment } from "../environment/ServerEnvironment.ts";
import { makePrimeTextGeneration } from "./PrimeTextGeneration.ts";
import { spawnPrimeRpcTransport } from "../provider/prime/PrimeRpcProcessTransport.ts";
import * as TextGeneration from "./TextGeneration.ts";

const INSTANCE = ProviderInstanceId.make("prime-agent");
const fakeSource = `#!/usr/bin/env node
import {createInterface} from 'node:readline'; import {appendFileSync} from 'node:fs';
const out=x=>process.stdout.write(JSON.stringify(x)+'\\n'); const log=x=>appendFileSync(process.env.MARKER,JSON.stringify(x)+'\\n');
const model={id:'model',name:'Model',api:'api',provider:'provider',baseUrl:'',reasoning:false,input:process.env.NO_IMAGE?'text':['text','image'],cost:{input:0,output:0,cacheRead:0,cacheWrite:0},contextWindow:1000,maxTokens:100,thinkingLevelMap:{}};
createInterface({input:process.stdin,crlfDelay:Infinity}).on('line',line=>{const c=JSON.parse(line); log(c); if(c.type==='get_state')return out({type:'response',id:c.id,command:c.type,success:true,data:{}}); if(c.type==='get_available_models')return out({type:'response',id:c.id,command:c.type,success:true,data:{models:[model]}}); if(c.type==='set_model')return out({type:'response',id:c.id,command:c.type,success:true,data:{}}); if(c.type!=='prompt')return; if(process.env.CRASH)process.exit(29); if(process.env.HANG)return; out({type:'response',id:c.id,command:c.type,success:true,data:{}}); if(process.env.BAD==='malformed')return out({type:'not-a-real-event'}); if(process.env.BAD==='unknown')return out({type:'mystery'}); if(process.env.BAD==='json') {out({type:'message_update',message:{},assistantMessageEvent:{delta:'not json'}});out({type:'turn_end',message:{},toolResults:[]});return;} const body=c.message.includes('git branch names')?'{"branch":" feat / PA-11 \","x":"ignored"}':c.message.includes('source control change request')?'{"title":"  Great title! ","body":"## Summary\\\\n- done"}':c.message.includes('T3 Code thread')?'{"title":"  A useful title  "}':'{"subject":"  Fix thing. ","body":"details"}'; out({type:'message_update',message:{},assistantMessageEvent:{delta:body.slice(0,Math.floor(body.length/2))}});out({type:'message_update',message:{},assistantMessageEvent:{delta:body.slice(Math.floor(body.length/2))}}); if(process.env.ENDSNAP)out({type:'message_end',message:{content:body}}); else out({type:'message_end',message:{content:body}}); out({type:'turn_end',message:{},toolResults:[]});});`;
const setup=Effect.acquireRelease(Effect.promise(async()=>{const root=await mkdtemp(join(tmpdir(),'prime-text-'));const cwd=join(root,'cwd');await (await import('node:fs/promises')).mkdir(cwd);const binary=join(root,'fake.mjs');const marker=join(root,'marker');await writeFile(binary,fakeSource);await chmod(binary,0o755);return {root,cwd,binary,marker};}),f=>Effect.promise(()=>rm(f.root,{recursive:true,force:true})));
const cfg=(f:any)=>Layer.succeed(ServerConfig.ServerConfig,ServerConfig.make({logLevel:"Error",traceMinLevel:"Info",traceTimingEnabled:true,traceBatchWindowMs:200,traceMaxBytes:10485760,traceMaxFiles:10,otlpTracesUrl:undefined,otlpMetricsUrl:undefined,otlpExportIntervalMs:10000,otlpServiceName:"t3-server",cwd:f.cwd,baseDir:f.root,stateDir:f.root,dbPath:join(f.root,"state.sqlite"),keybindingsConfigPath:join(f.root,"keybindings.json"),settingsPath:join(f.root,"settings.json"),providerStatusCacheDir:join(f.root,"cache"),worktreesDir:join(f.root,"worktrees"),attachmentsDir:join(f.root,"attachments"),logsDir:join(f.root,"logs"),serverLogPath:join(f.root,"logs/server.log"),serverTracePath:join(f.root,"logs/server.trace"),providerLogsDir:join(f.root,"logs/provider"),providerEventLogPath:join(f.root,"logs/provider/events"),terminalLogsDir:join(f.root,"logs/terminal"),anonymousIdPath:join(f.root,"anonymous"),environmentIdPath:join(f.root,"environment"),serverRuntimeStatePath:join(f.root,"runtime"),secretsDir:join(f.root,"secrets"),mode:"web",autoBootstrapProjectFromCwd:false,logWebSocketEvents:false,tailscaleServeEnabled:false,tailscaleServePort:443,port:0,host:undefined,desktopBootstrapToken:undefined,desktopTelemetryFd:undefined,desktopTelemetryControlFd:undefined,resourceMonitorPath:undefined,staticDir:undefined,devUrl:undefined,devAllowedOrigins:[],noBrowser:false,startupPresentation:"browser"}));
const env=Layer.succeed(ServerEnvironment,{getEnvironmentId:Effect.succeed(EnvironmentId.make('env')),getDescriptor:Effect.die('unused')});
const make=(f:any,extra:any={})=>makePrimeTextGeneration({binaryPath:f.binary},{instanceId:INSTANCE,timeoutMs:extra.timeoutMs??1000,environment:{PATH:process.env.PATH},launch:(command,args,options)=>spawnPrimeRpcTransport(command,args,{...(options??{}),env:{...(options?.env??{}),MARKER:f.marker,...extra.env}})}).pipe(Effect.provide(Layer.merge(cfg(f),env)));
const sel:any={instanceId:INSTANCE,model:'model',nativeIdentity:{provider:'provider',modelId:'model'}};
const base=(f:any)=>({cwd:f.cwd,modelSelection:sel});
const commands=(f:any)=>Effect.promise(async()=>{const s=await readFile(f.marker,'utf8').catch(()=> '');return s.trim().split('\n').filter(Boolean).map((line:string)=>JSON.parse(line))});
const expectFail=(e:any)=>Effect.match(e,{onFailure:()=>true,onSuccess:()=>false});

describe('PrimeTextGeneration real RPC contract',()=>{
 it.effect('generates and sanitizes all four structured outputs',()=>Effect.scoped(Effect.gen(function*(){const f=yield* setup;const g=yield* make(f);const c=yield* g.generateCommitMessage({...base(f),branch:'main',stagedSummary:'x',stagedPatch:'y'});assert.equal(c.subject,'Fix thing');const p=yield* g.generatePrContent({...base(f),baseBranch:'main',headBranch:'x',commitSummary:'x',diffSummary:'x',diffPatch:'x'});assert.equal(p.title,'Great title!');const b=yield* g.generateBranchName({...base(f),message:'branch'});assert.equal(b.branch,'feature/feat-/-pa-11');const t=yield* g.generateThreadTitle({...base(f),message:'thread title'});assert.equal(t.title,'A useful title');})));
 it.effect('sends exact provider/model commands',()=>Effect.scoped(Effect.gen(function*(){const f=yield* setup;const g=yield* make(f);yield* g.generateThreadTitle({...base(f),message:'thread title'});const cs=yield* commands(f);const modelCommand=cs.filter((x:any)=>x.type==='set_model').at(-1);assert.equal(modelCommand.provider,'provider');assert.equal(modelCommand.modelId,'model');assert.equal(cs.filter((x:any)=>x.type==='get_available_models').length,1);}))); 
 it.effect('rejects missing and image-unsupported models',()=>Effect.scoped(Effect.gen(function*(){const f=yield* setup;const bad={...sel,nativeIdentity:{provider:'other',modelId:'no'}};const g=yield* make(f);assert.equal(yield* expectFail(g.generateThreadTitle({...base(f),modelSelection:bad,message:'x'})),true);const h=yield* make(f,{env:{NO_IMAGE:'1'}});const a:any={type:'image',id:'foreign',name:'x.png',mimeType:'image/png',sizeBytes:1};assert.equal(yield* expectFail(h.generateBranchName({...base(f),message:'x',attachments:[a]})),true);}))); 
 it.effect('fails foreign attachment before prompt',()=>Effect.scoped(Effect.gen(function*(){const f=yield* setup;const g=yield* make(f);const a:any={type:'image',id:'foreign',name:'x.png',mimeType:'image/png',sizeBytes:1};assert.equal(yield* expectFail(g.generateBranchName({...base(f),message:'x',attachments:[a]})),true);assert.equal((yield* commands(f)).some((x:any)=>x.type==='prompt'),false);}))); 
 it.effect('fails malformed JSON and events closed',()=>Effect.scoped(Effect.gen(function*(){const f=yield* setup;for(const mode of ['json','malformed','unknown']){const g=yield* make(f,{env:{BAD:mode}});assert.equal(yield* expectFail(g.generateThreadTitle({...base(f),message:'thread title'})),true);}})));
 it.effect('crash, timeout, then next operation succeeds and sentinel survives',()=>Effect.scoped(Effect.gen(function*(){const f=yield* setup;yield* Effect.promise(()=>writeFile(join(f.root,'sentinel'),'keep'));const crash=yield* make(f,{env:{CRASH:'1'}});assert.equal(yield* expectFail(crash.generateThreadTitle({...base(f),message:'thread title'})),true);const started=Date.now();const slow=yield* make(f,{timeoutMs:100,env:{HANG:'1'}});assert.equal(yield* expectFail(slow.generateThreadTitle({...base(f),message:'thread title'})),true);assert.ok(Date.now()-started<2000);const next=yield* make(f);assert.equal((yield* next.generateThreadTitle({...base(f),message:'thread title'})).title,'A useful title');assert.equal(yield* Effect.promise(()=>readFile(join(f.root,'sentinel'),'utf8')),'keep');})));
 it.effect('sends validated owned image bytes and MIME for branch generation',()=>Effect.scoped(Effect.gen(function*(){const f=yield* setup;yield* Effect.promise(()=>mkdir(join(f.root,'attachments'),{recursive:true}));yield* Effect.promise(()=>writeFile(join(f.root,'attachments','owned.png'),Buffer.from([1,2,3])));const g=yield* make(f);const image:any={type:'image',id:'owned',name:'owned.png',mimeType:'image/png',sizeBytes:3};yield* g.generateBranchName({...base(f),message:'branch',attachments:[image]});const cs=yield* commands(f);const prompt=cs.find((x:any)=>x.type==='prompt');assert.equal(prompt.images[0].mimeType,'image/png');assert.equal(prompt.images[0].data,Buffer.from([1,2,3]).toString('base64'));})));
 it.effect('records exact child ownership as stopped after terminal',()=>Effect.scoped(Effect.gen(function*(){const f=yield* setup;const g=yield* make(f);yield* g.generateThreadTitle({...base(f),message:'thread title'});const files=yield* Effect.promise(()=>readdir(join(f.root,'userdata','prime','v1'),{recursive:true}));const ownership=files.find((x:any)=>String(x).endsWith('.json'));assert.ok(ownership);const record=JSON.parse(yield* Effect.promise(()=>readFile(join(f.root,'userdata','prime','v1',String(ownership)),'utf8')));assert.equal(record.processStopped,true);assert.ok(record.process.pid>0);assert.ok(record.process.startToken.length>0);}))); 
});
