import { describe, expect, it } from "@effect/vitest";
import { ProviderRuntimeEvent, ThreadId } from "@t3tools/contracts";
import * as Schema from "effect/Schema";
import { PrimeEventNormalizer } from "./PrimeEventNormalizer.ts";
const make=()=>new PrimeEventNormalizer(ThreadId.make("thread-test"),{providerInstanceId:"prime-agent",now:()=>"2020-01-01T00:00:00.000Z"});
const known=(value: any)=>({_tag:"known-event" as const,value});
describe("PrimeEventNormalizer",()=>{
 it("maps agent, turn and message lifecycle with exactly-once terminal",()=>{const n=make();const input=[{type:"agent_start"},{type:"turn_start"},{type:"message_start",message:{role:"assistant"}},{type:"message_update",message:{role:"assistant",usage:{totalTokens:7}},assistantMessageEvent:{type:"text_delta",delta:"hello"}},{type:"message_end",message:{role:"assistant"}},{type:"turn_end",message:{},toolResults:[]},{type:"agent_end",messages:[]},{type:"agent_end",messages:[]}];const out=input.flatMap(e=>n.drain(known(e) as any));expect(out.map(x=>x.type)).toEqual(["session.state.changed","thread.started","turn.started","item.started","content.delta","thread.token-usage.updated","item.completed","turn.completed","session.exited"]);expect(out.filter(x=>x.type==="turn.completed")).toHaveLength(1);});
 it("maps reasoning separately",()=>{const n=make();n.drain(known({type:"turn_start"}) as any);n.drain(known({type:"message_start",message:{role:"assistant"}}) as any);const out=n.drain(known({type:"message_update",message:{role:"assistant"},assistantMessageEvent:{type:"reasoning_delta",delta:"why"}}) as any);expect((out[0] as any).payload).toMatchObject({streamKind:"reasoning_text",delta:"why"});});
 it("maps tool lifecycle failure",()=>{const n=make();n.drain(known({type:"turn_start"}) as any);const out=[{type:"tool_execution_start",toolCallId:"x",toolName:"shell",args:{cmd:"x"}},{type:"tool_execution_end",toolCallId:"x",toolName:"shell",result:"bad",isError:true}].flatMap(e=>n.drain(known(e) as any));expect(out.map(x=>x.type)).toEqual(["item.started","item.completed"]);expect((out[1] as any).payload.status).toBe("failed");});
 it("coalesces accumulated tool snapshots linearly",()=>{const n=make();n.drain(known({type:"turn_start"}) as any);const events=[];for(let i=1;i<=100;i++)events.push(...n.drain(known({type:"tool_execution_update",toolCallId:"x",toolName:"sh",args:{},partialResult:"x".repeat(i)}) as any));expect(events).toHaveLength(100);expect(events.reduce((sum,e)=>sum+((e as any).payload.delta?.length??0),0)).toBe(100);});
 it("emits replacement only for non-prefix material change and ignores duplicate",()=>{const n=make();const a=n.drain(known({type:"tool_execution_update",toolCallId:"x",toolName:"sh",args:{},partialResult:"abc"}) as any);const b=n.drain(known({type:"tool_execution_update",toolCallId:"x",toolName:"sh",args:{},partialResult:"xyz"}) as any);const c=n.drain(known({type:"tool_execution_update",toolCallId:"x",toolName:"sh",args:{},partialResult:"xyz"}) as any);expect(a[0]?.type).toBe("content.delta");expect(b[0]?.type).toBe("item.updated");expect(c).toEqual([]);});
 it("warns once per unknown additive event and continues",()=>{const n=make();const u={_tag:"unknown-event" as const,type:"future",value:{}};expect(n.drain(u as any)[0]?.type).toBe("runtime.warning");expect(n.drain(u as any)).toEqual([]);expect(n.drain(known({type:"turn_start"}) as any)[0]?.type).toBe("turn.started");});
 it("terminalizes transport failure once",()=>{const n=make();n.drain(known({type:"turn_start"}) as any);const first=n.stop("crash"), second=n.stop("again");expect(first.map(x=>x.type)).toEqual(["turn.completed","runtime.error","session.exited"]);expect(second).toEqual([]);});

 it("emits contract-valid canonical records",()=>{const n=make();const records=[...n.drain(known({type:"turn_start"}) as any),...n.drain(known({type:"message_start",message:{role:"assistant"}}) as any),...n.drain(known({type:"message_update",message:{role:"assistant",usage:{totalTokens:2}},assistantMessageEvent:{type:"reasoning_delta",delta:"x"}}) as any),...n.stop("boom")];for(const record of records)expect(()=>Schema.decodeUnknownSync(ProviderRuntimeEvent)(record)).not.toThrow();});

});
