// The exact remover has to observe raw inode identity across a rename, which
// only the node fs primitives expose; `FileSystem` cannot express it.
// @effect-diagnostics nodeBuiltinImport:off
// Cleanup and lease stores expose promise-facing ports, so recovery runs them
// against the SQL client captured before entering those callbacks.
// @effect-diagnostics runEffectInsideEffect:off
// Startup recovery reads lease expiry inside promise callbacks, where there is
// no fiber to carry an Effect Clock.
// @effect-diagnostics globalDate:off
import * as NodeFSP from "node:fs/promises";
import * as NodePath from "node:path";

import * as Effect from "effect/Effect";
import * as Option from "effect/Option";
import * as SqlClient from "effect/unstable/sql/SqlClient";

import { primeResumeScopeFromKey, primeResumeScopeKey } from "@t3tools/contracts";

import { redactPrimeCleanupReport, resumePrimeCleanup } from "./PrimeDurableCleanup.ts";
import { makePrimeCleanupJournalSqlStore } from "./PrimeDurableCleanupSql.ts";
import type { PrimeOwnedResource } from "./PrimeOwnership.ts";
import { primeHomeFingerprint } from "./PrimeResourceLayout.ts";
import { primeLeaseIso } from "./PrimeSessionLease.ts";
import { makePrimeSessionLeaseSqlStore } from "./PrimeSessionLeaseSql.ts";

/**
 * PA-B05 — the production entry point for resuming durable Prime cleanup.
 *
 * This is the only caller of `resumePrimeCleanup` in the running server. It
 * resumes only rows owned by this environment, provider instance and T3 home.
 * It never plans a new deletion: it only finishes a confirmed deletion that a
 * crash interrupted after the durable journal had already been written.
 */

const contained = (root: string, child: string) => {
  const path = NodePath.relative(NodePath.resolve(root), NodePath.resolve(child));
  return path === "" || (!path.startsWith("..") && !NodePath.isAbsolute(path));
};

/** Safely removes one exact proven inode by quarantine rename. */
const makeExactRemover = async (resource: PrimeOwnedResource): Promise<"removed" | "retained"> => {
  const path = NodePath.resolve(resource.path);
  const parent = NodePath.dirname(path);
  let parentIdentity: { readonly dev: bigint; readonly ino: bigint };
  try {
    const parentStat = await NodeFSP.lstat(parent, { bigint: true });
    if (parentStat.isSymbolicLink() || !parentStat.isDirectory()) return "retained";
    parentIdentity = { dev: parentStat.dev, ino: parentStat.ino };
    const parentReal = await NodeFSP.realpath(parent);
    if (!contained(parentReal, path)) return "retained";
  } catch {
    return "retained";
  }

  let before;
  try {
    before = await NodeFSP.lstat(path, { bigint: true });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return "removed";
    return "retained";
  }
  if (
    before.isSymbolicLink() ||
    String(before.dev) !== resource.identity.dev ||
    String(before.ino) !== resource.identity.ino
  ) {
    return "retained";
  }

  // The basename is generated by the exact Prime layout; do not accept any
  // caller-provided quarantine name or random destination.
  const quarantine = NodePath.join(parent, `.${NodePath.basename(path)}.quarantine`);
  try {
    const parentStat = await NodeFSP.lstat(parent, { bigint: true });
    const check = await NodeFSP.lstat(path, { bigint: true });
    if (
      parentStat.isSymbolicLink() ||
      parentStat.dev !== parentIdentity.dev ||
      parentStat.ino !== parentIdentity.ino ||
      check.isSymbolicLink() ||
      check.dev !== before.dev ||
      check.ino !== before.ino
    ) {
      return "retained";
    }
    try {
      await NodeFSP.lstat(quarantine);
      return "retained";
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") return "retained";
    }
    await NodeFSP.rename(path, quarantine);
    const parentAfter = await NodeFSP.lstat(parent, { bigint: true });
    if (
      parentAfter.isSymbolicLink() ||
      parentAfter.dev !== parentIdentity.dev ||
      parentAfter.ino !== parentIdentity.ino
    ) {
      return "retained";
    }
    // Final awaited observation before deletion binds the quarantine pathname
    // to the exact inode that was renamed out of the active namespace.
    const moved = await NodeFSP.lstat(quarantine, { bigint: true });
    if (moved.isSymbolicLink() || moved.dev !== before.dev || moved.ino !== before.ino) {
      return "retained";
    }
    await NodeFSP.rm(quarantine, { recursive: true, force: false });
    return "removed";
  } catch {
    return "retained";
  }
};

export const resumeUnfinishedPrimeCleanup = (input: {
  readonly environmentId: string;
  readonly instanceId: string;
  readonly home: string;
}): Effect.Effect<readonly ReturnType<typeof redactPrimeCleanupReport>[]> =>
  Effect.gen(function* () {
    const sql = yield* Effect.serviceOption(SqlClient.SqlClient);
    if (Option.isNone(sql)) return [];

    const journal = yield* makePrimeCleanupJournalSqlStore().pipe(
      Effect.provideService(SqlClient.SqlClient, sql.value),
    );
    const entries = yield* Effect.promise(() => journal.listUnfinished());
    const reports: ReturnType<typeof redactPrimeCleanupReport>[] = [];
    const homeFingerprint = primeHomeFingerprint(input.home);

    for (const entry of entries) {
      const scope = primeResumeScopeFromKey(entry.scopeKey);
      if (scope === undefined) continue;
      if (
        scope.environmentId !== input.environmentId ||
        scope.providerInstanceId !== input.instanceId ||
        scope.homeFingerprint !== homeFingerprint
      ) {
        continue;
      }

      const leaseStore = yield* makePrimeSessionLeaseSqlStore({
        scope,
        nowIso: () => primeLeaseIso(Date.now()),
      }).pipe(Effect.provideService(SqlClient.SqlClient, sql.value));
      const guard = async () => {
        const record = await leaseStore.read(primeResumeScopeKey(scope));
        return record !== undefined && record.expiresAtMs > Date.now()
          ? ({ status: "leaseHeld", generation: record.generation } as const)
          : ({ status: "clear" } as const);
      };

      const report = yield* Effect.promise(async () => {
        try {
          return await resumePrimeCleanup({
            home: input.home,
            scope,
            journal,
            guard,
            proof: { processMatches: async () => false },
            cleanup: {
              stopProcess: async () => {
                throw new Error("process was not proven stopped");
              },
              removeOwnedResource: makeExactRemover,
            },
            now: () => new Date().toISOString(),
          });
        } catch {
          return undefined;
        }
      });
      if (report !== undefined) reports.push(redactPrimeCleanupReport(report));
    }

    return reports;
  });
