import * as Crypto from "effect/Crypto";
import { Atom } from "effect/unstable/reactivity";

import { createAtomCommandScheduler, createEnvironmentCommand } from "./runtime.ts";
import {
  type ArchiveThreadInput,
  type CreateThreadInput,
  type DeleteThreadInput,
  type InterruptThreadTurnInput,
  type SteerThreadInput,
  type AddThreadFollowUpInput,
  type RequestThreadCompactionInput,
  type RefreshThreadUsageInput,
  type RefreshThreadCommandsInput,
  type ObserveThreadAgentInput,
  type UnobserveThreadAgentInput,
  type CreateThreadHeartbeatInput,
  type PauseThreadHeartbeatInput,
  type ResumeThreadHeartbeatInput,
  type DeleteThreadHeartbeatInput,
  type RenameThreadSessionInput,
  type ForkThreadSessionInput,
  recoverPrimeResume,
  type RecoverPrimeResumeInput,
  type RespondToThreadApprovalInput,
  type RespondToThreadUserInputInput,
  type RevertThreadCheckpointInput,
  type SetThreadInteractionModeInput,
  type SetThreadRuntimeModeInput,
  type PinThreadInput,
  type ReorderPinnedThreadInput,
  type SettleThreadInput,
  type SnoozeThreadInput,
  type StartThreadTurnInput,
  type StopThreadSessionInput,
  type UnarchiveThreadInput,
  type UnpinThreadInput,
  type UnsettleThreadInput,
  type UnsnoozeThreadInput,
  type UpdateThreadMetadataInput,
  archiveThread,
  createThread,
  deleteThread,
  interruptThreadTurn,
  steerThread,
  addThreadFollowUp,
  requestThreadCompaction,
  observeThreadAgent,
  unobserveThreadAgent,
  createThreadHeartbeat,
  pauseThreadHeartbeat,
  resumeThreadHeartbeat,
  deleteThreadHeartbeat,
  renameThreadSession,
  forkThreadSession,
  refreshThreadUsage,
  refreshThreadCommands,
  respondToThreadApproval,
  respondToThreadUserInput,
  revertThreadCheckpoint,
  setThreadInteractionMode,
  setThreadRuntimeMode,
  pinThread,
  reorderPinnedThread,
  settleThread,
  snoozeThread,
  startThreadTurn,
  stopThreadSession,
  unarchiveThread,
  unpinThread,
  unsettleThread,
  unsnoozeThread,
  updateThreadMetadata,
} from "../operations/commands.ts";
import type { EnvironmentRegistry } from "../connection/registry.ts";

export type {
  ArchiveThreadInput,
  CreateThreadInput,
  DeleteThreadInput,
  InterruptThreadTurnInput,
  SteerThreadInput,
  AddThreadFollowUpInput,
  RequestThreadCompactionInput,
  RefreshThreadUsageInput,
  RespondToThreadApprovalInput,
  RespondToThreadUserInputInput,
  RevertThreadCheckpointInput,
  SetThreadInteractionModeInput,
  SetThreadRuntimeModeInput,
  PinThreadInput,
  ReorderPinnedThreadInput,
  SettleThreadInput,
  SnoozeThreadInput,
  StartThreadTurnInput,
  StopThreadSessionInput,
  UnarchiveThreadInput,
  UnpinThreadInput,
  UnsettleThreadInput,
  UnsnoozeThreadInput,
  UpdateThreadMetadataInput,
} from "../operations/commands.ts";

export function createThreadEnvironmentAtoms<R, E>(
  runtime: Atom.AtomRuntime<EnvironmentRegistry | Crypto.Crypto | R, E>,
) {
  const scheduler = createAtomCommandScheduler();
  const concurrency = {
    mode: "serial" as const,
    key: ({ environmentId, input }: { environmentId: string; input: { threadId: string } }) =>
      JSON.stringify([environmentId, input.threadId]),
  };
  return {
    create: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:create",
      execute: (input: CreateThreadInput) => createThread(input),
      scheduler,
      concurrency,
    }),
    delete: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:delete",
      execute: (input: DeleteThreadInput) => deleteThread(input),
      scheduler,
      concurrency,
    }),
    archive: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:archive",
      execute: (input: ArchiveThreadInput) => archiveThread(input),
      scheduler,
      concurrency,
    }),
    unarchive: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unarchive",
      execute: (input: UnarchiveThreadInput) => unarchiveThread(input),
      scheduler,
      concurrency,
    }),
    settle: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:settle",
      execute: (input: SettleThreadInput) => settleThread(input),
      scheduler,
      concurrency,
    }),
    unsettle: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unsettle",
      execute: (input: UnsettleThreadInput) => unsettleThread(input),
      scheduler,
      concurrency,
    }),
    snooze: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:snooze",
      execute: (input: SnoozeThreadInput) => snoozeThread(input),
      scheduler,
      concurrency,
    }),
    unsnooze: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unsnooze",
      execute: (input: UnsnoozeThreadInput) => unsnoozeThread(input),
      scheduler,
      concurrency,
    }),
    pin: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:pin",
      execute: (input: PinThreadInput) => pinThread(input),
      scheduler,
      concurrency,
    }),
    unpin: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unpin",
      execute: (input: UnpinThreadInput) => unpinThread(input),
      scheduler,
      concurrency,
    }),
    reorderPin: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:reorder-pin",
      execute: (input: ReorderPinnedThreadInput) => reorderPinnedThread(input),
      scheduler,
      concurrency,
    }),
    updateMetadata: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:update-metadata",
      execute: (input: UpdateThreadMetadataInput) => updateThreadMetadata(input),
      scheduler,
      concurrency,
    }),
    setRuntimeMode: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:set-runtime-mode",
      execute: (input: SetThreadRuntimeModeInput) => setThreadRuntimeMode(input),
      scheduler,
      concurrency,
    }),
    setInteractionMode: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:set-interaction-mode",
      execute: (input: SetThreadInteractionModeInput) => setThreadInteractionMode(input),
      scheduler,
      concurrency,
    }),
    startTurn: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:start-turn",
      execute: (input: StartThreadTurnInput) => startThreadTurn(input),
      scheduler,
      concurrency,
    }),
    interruptTurn: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:interrupt-turn",
      execute: (input: InterruptThreadTurnInput) => interruptThreadTurn(input),
      scheduler,
      concurrency,
    }),
    steer: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:steer",
      execute: (input: SteerThreadInput) => steerThread(input),
      scheduler,
      concurrency,
    }),
    addFollowUp: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:add-follow-up",
      execute: (input: AddThreadFollowUpInput) => addThreadFollowUp(input),
      scheduler,
      concurrency,
    }),
    requestCompaction: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:request-compaction",
      execute: (input: RequestThreadCompactionInput) => requestThreadCompaction(input),
      scheduler,
      concurrency,
    }),
    refreshUsage: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:refresh-usage",
      execute: (input: RefreshThreadUsageInput) => refreshThreadUsage(input),
      scheduler,
      concurrency,
    }),
    observeAgent: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:observe-agent",
      execute: (input: ObserveThreadAgentInput) => observeThreadAgent(input),
      scheduler,
      concurrency,
    }),
    unobserveAgent: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unobserve-agent",
      execute: (input: UnobserveThreadAgentInput) => unobserveThreadAgent(input),
      scheduler,
      concurrency,
    }),
    createHeartbeat: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:create-heartbeat",
      execute: (input: CreateThreadHeartbeatInput) => createThreadHeartbeat(input),
      scheduler,
      concurrency,
    }),
    pauseHeartbeat: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:pause-heartbeat",
      execute: (input: PauseThreadHeartbeatInput) => pauseThreadHeartbeat(input),
      scheduler,
      concurrency,
    }),
    resumeHeartbeat: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:resume-heartbeat",
      execute: (input: ResumeThreadHeartbeatInput) => resumeThreadHeartbeat(input),
      scheduler,
      concurrency,
    }),
    deleteHeartbeat: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:delete-heartbeat",
      execute: (input: DeleteThreadHeartbeatInput) => deleteThreadHeartbeat(input),
      scheduler,
      concurrency,
    }),
    renameSession: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:rename-session",
      execute: (input: RenameThreadSessionInput) => renameThreadSession(input),
      scheduler,
      concurrency,
    }),
    forkSession: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:fork-session",
      execute: (input: ForkThreadSessionInput) => forkThreadSession(input),
      scheduler,
      concurrency,
    }),
    recoverPrimeResume: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:recover-prime-resume",
      execute: (input: RecoverPrimeResumeInput) => recoverPrimeResume(input),
      scheduler,
      concurrency,
    }),
    refreshCommands: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:refresh-commands",
      execute: (input: RefreshThreadCommandsInput) => refreshThreadCommands(input),
      scheduler,
      concurrency,
    }),
    respondToApproval: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:respond-to-approval",
      execute: (input: RespondToThreadApprovalInput) => respondToThreadApproval(input),
      scheduler,
      concurrency,
    }),
    respondToUserInput: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:respond-to-user-input",
      execute: (input: RespondToThreadUserInputInput) => respondToThreadUserInput(input),
      scheduler,
      concurrency,
    }),
    revertCheckpoint: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:revert-checkpoint",
      execute: (input: RevertThreadCheckpointInput) => revertThreadCheckpoint(input),
      scheduler,
      concurrency,
    }),
    stopSession: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:stop-session",
      execute: (input: StopThreadSessionInput) => stopThreadSession(input),
      scheduler,
      concurrency,
    }),
  };
}
