// @effect-diagnostics nodeBuiltinImport:off
import { assert, describe, it } from "@effect/vitest";
import { ProviderDriverKind, ProviderInstanceId, ThreadId } from "@t3tools/contracts";
import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import * as Effect from "effect/Effect";

import { spawnPrimeRpcTransport } from "../prime/PrimeRpcProcessTransport.ts";
import { makePrimeAdapter } from "./PrimeAdapter.ts";
const PROVIDER=ProviderDriverKind.make("prime-agent"), INSTANCE=ProviderInstanceId.make("prime-agent");
const fake=`#!/usr/bin/env node
import { appendFileSync } from "node:fs"; import { createInterface } from "node:readline";
createInterface({input:process.stdin}).on("line",line=>{const c=JSON.parse(line);appendFileSync(process.env.MARKER,JSON.stringify(c)+"\\n");const data=c.type==="get_available_models"?{models:[{id:"same",name:"A",api:"x",provider:"alpha",baseUrl:"",reasoning:true,input:["text","image"],cost:{input:0,output:0,cacheRead:0,cacheWrite:0},contextWindow:1,maxTokens:1,thinkingLevelMap:{high:"high",off:null}},{id:"same",name:"B",api:"x",provider:"beta",baseUrl:"",reasoning:false,input:["text"],cost:{input:0,output:0,cacheRead:0,cacheWrite:0},contextWindow:1,maxTokens:1}]}:{state:"idle"};process.stdout.write(JSON.stringify({type:"response",id:c.id,command:c.type,success:true,data})+"\\n")});`;
const input=(cwd:string)=>({threadId:ThreadId.make("thread-turn"),provider:PROVIDER,providerInstanceId:INSTANCE,cwd,runtimeMode:"approval-required" as const});
const setup=Effect.acquireRelease(Effect.promise(async()=>{const root=await mkdtemp(join(tmpdir(),"prime-turn-")),cwd=join(root,"workspace"),attachmentsDir=join(root,"attachments"),binary=join(root,"fake.mjs"),marker=join(root,"marker");await mkdir(cwd);await mkdir(attachmentsDir);await writeFile(binary,fake);await chmod(binary,0o755);return{root,cwd,attachmentsDir,binary,marker}}),f=>Effect.promise(()=>rm(f.root,{recursive:true,force:true})));
const commands=(p:string)=>Effect.promise(async()=>(await readFile(p,"utf8").catch(()=>"")).trim().split("\n").filter(Boolean).map((line)=>JSON.parse(line)));
describe("PrimeAdapter turn input",()=>{
 it("preflights exact native model, thinking, text and image before prompt",()=>Effect.scoped(Effect.gen(function*(){const f=yield* setup;const adapter=yield* makePrimeAdapter({binaryPath:f.binary},{instanceId:INSTANCE,environmentId:"env",home:join(f.root,"home"),attachmentsDir:f.attachmentsDir,enabled:true,launch:(c,a,o)=>spawnPrimeRpcTransport(c,a,{...(o??{}),env:{...(o?.env??{}),MARKER:f.marker}})});yield* adapter.startSession(input(f.cwd));const text={type:"text" as const,id:"thread-turn-11111111-1111-4111-8111-111111111111",name:"error.log",mimeType:"text/plain",sizeBytes:4};const image={type:"image" as const,id:"thread-turn-22222222-2222-4222-8222-222222222222",name:"shot.jpg",mimeType:"image/png",sizeBytes:3};yield* Effect.promise(()=>Promise.all([writeFile(join(f.attachmentsDir,`${text.id}.log`),"boom"),writeFile(join(f.attachmentsDir,`${image.id}.png`),Buffer.from([1,2,3]))]));const result=yield* adapter.sendTurn({threadId:input(f.cwd).threadId,input:"debug",attachments:[text,image],modelSelection:{instanceId:INSTANCE,model:"same",nativeIdentity:{provider:"alpha",modelId:"same"},options:[{id:"thinkingLevel",value:"high"}]}});assert.ok(result.turnId);const all=yield* commands(f.marker);assert.deepStrictEqual(all.map(c=>c.type),["get_state","get_available_models","set_model","set_thinking_level","prompt"]);assert.match(all[4].message,/error.log/);assert.equal(all[4].images[0].data,"AQID");})));
 it("rejects ambiguous legacy selection and unsupported image before model mutation",()=>Effect.scoped(Effect.gen(function*(){const f=yield* setup;const adapter=yield* makePrimeAdapter({binaryPath:f.binary},{instanceId:INSTANCE,environmentId:"env",home:join(f.root,"home"),attachmentsDir:f.attachmentsDir,enabled:true,launch:(c,a,o)=>spawnPrimeRpcTransport(c,a,{...(o??{}),env:{...(o?.env??{}),MARKER:f.marker}})});yield* adapter.startSession(input(f.cwd));const ambiguous=yield* Effect.exit(adapter.sendTurn({threadId:input(f.cwd).threadId,input:"x",modelSelection:{instanceId:INSTANCE,model:"same"}}));assert.equal(ambiguous._tag,"Failure");assert.deepStrictEqual((yield* commands(f.marker)).map(c=>c.type),["get_state","get_available_models"]);})));
});
